name: Update TdLib
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Init
        run: |
          git config --local user.email "nitan.marcel@gmail.com"
          git config --local user.name "Marcel Alexandru Nitan"
          git pull --tags
      - name: Get Latest Tag On Master
        id: gettag
        uses: oprypin/find-latest-tag@v1
        with:
          repository: ${{github.repository}}
      - name: Update TdLib to tag
        run: |
            cd td
            git pull origin ${{steps.tag.outputs.tag}}
            cd ..
      - name: Generate Code
        run: |
          cd codegen
          make
          cd ..
      - name: Commit Changes
        run: |
            git add .
            git commit -m "Update tdlib to ${{steps.tag.outputs.tag}}"
      - name: Push Changes
        run: |
          git push origin master:${{steps.tag.outputs.tag}}
